service: express-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  memorySize: 512
  timeout: 10

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /